const nodes = [
  { id: "html", label: "HTML", group: "markup", depth: 1 },
  { id: "css", label: "CSS", group: "markup", depth: 1 },
  { id: "javascript", label: "JavaScript", group: "scripting", depth: 1 },
  { id: "react", label: "React", group: "libraries", depth: 2 },
  { id: "angular", label: "Angular", group: "libraries", depth: 2 },
  { id: "vue", label: "Vue.js", group: "libraries", depth: 2 },
  { id: "jquery", label: "jQuery", group: "libraries", depth: 2 },
  { id: "bootstrap", label: "Bootstrap", group: "libraries", depth: 2 },
  { id: "sass", label: "Sass", group: "css-preprocessors", depth: 2 },
  { id: "less", label: "Less", group: "css-preprocessors", depth: 2 },
  { id: "stylus", label: "Stylus", group: "css-preprocessors", depth: 2 },
  { id: "typescript", label: "TypeScript", group: "scripting", depth: 2 },
  { id: "babel", label: "Babel", group: "build-tools", depth: 3 },
  { id: "webpack", label: "Webpack", group: "build-tools", depth: 3 },
  { id: "gulp", label: "Gulp", group: "build-tools", depth: 3 },
  { id: "redux", label: "Redux", group: "state-management", depth: 3 },
  { id: "mobx", label: "MobX", group: "state-management", depth: 3 },
  { id: "ngrx", label: "NGRX", group: "state-management", depth: 3 },
  { id: "graphql", label: "GraphQL", group: "api-tools", depth: 3 },
  { id: "rest", label: "REST", group: "api-tools", depth: 3 },
  { id: "storybook", label: "Storybook", group: "ui-frameworks", depth: 3 },
  { id: "jest", label: "Jest", group: "testing", depth: 3 },
  { id: "cypress", label: "Cypress", group: "testing", depth: 3 },
  { id: "mocha", label: "Mocha", group: "testing", depth: 3 },
  { id: "enzyme", label: "Enzyme", group: "testing", depth: 3 },
  { id: "eslint", label: "ESLint", group: "linting", depth: 4 },
  { id: "prettier", label: "Prettier", group: "linting", depth: 4 },
  { id: "stylelint", label: "Stylelint", group: "linting", depth: 4 },
  { id: "husky", label: "Husky", group: "git-hooks", depth: 4 },
  { id: "lint-staged", label: "Lint-staged", group: "git-hooks", depth: 4 },
  { id: "babel-eslint", label: "Babel-eslint", group: "linting", depth: 4 },
  { id: "standard", label: "Standard", group: "linting", depth: 4 },
  { id: "nextjs", label: "Next.js", group: "frameworks", depth: 4 },
];
const links = [
  { source: "html", target: "css" },
  { source: "javascript", target: "react" },
  { source: "javascript", target: "angular" },
  { source: "javascript", target: "vue" },
  { source: "javascript", target: "jquery" },
  { source: "css", target: "sass" },
  { source: "css", target: "less" },
  { source: "css", target: "stylus" },
  { source: "javascript", target: "typescript" },
  { source: "typescript", target: "react" },
  { source: "typescript", target: "angular" },
  { source: "typescript", target: "vue" },
  { source: "typescript", target: "jquery" },
  { source: "typescript", target: "redux" },
  { source: "typescript", target: "mobx" },
  { source: "typescript", target: "ngrx" },
  { source: "typescript", target: "graphql" },
  { source: "typescript", target: "rest" },
  { source: "react", target: "storybook" },
  { source: "react", target: "redux" },
  { source: "react", target: "mobx" },
  { source: "react", target: "ngrx" },
  { source: "angular", target: "ngrx" },
  { source: "redux", target: "mobx" },
  { source: "redux", target: "ngrx" },
  { source: "mobx", target: "ngrx" },
  { source: "react", target: "jest" },
  { source: "react", target: "cypress" },
  { source: "angular", target: "mocha" },
  { source: "angular", target: "enzyme" },
  { source: "eslint", target: "prettier" },
  { source: "eslint", target: "babel-eslint" },
  { source: "eslint", target: "standard" },
  { source: "husky", target: "lint-staged" },
  { source: "javascript", target: "babel" },
  { source: "javascript", target: "webpack" },
  { source: "javascript", target: "gulp" },
  { source: "graphql", target: "rest" },
  { source: "react", target: "nextjs" },
];

export const technologiesGraphData = { nodes, links };
